# Build
custom_build(
ref='dispatcher-service',
command='./gradlew bootBuildImage --imageName $EXPECTED_REF',
deps=['build.gradle','src']
)

# Deploy
k8s_yaml(kustomize('k8s'))

# Manage
k8s_resource('dispatcher-service',port_forwards=['9003'])
