# Build
custom_build(
ref='config-service',
command='./gradlew bootBuildImage --imageName $EXPECTED_REF',
deps=['build.gradle','src']
)

# Deploy
k8s_yaml(kustomize('k8s'))

# Manage
k8s_resource('config-service',port_forwards=['8888'])