name: Commit Stage
on: push
jobs:
  build:
    name: Build and Test ${{ matrix.project }}
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        project: [
          catalog-service
        ]